{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
          location ~* /list-credential/ {
              deny all;
              return 403;
          }

          location ~* /webhook/topic/ {
            deny all;
            return 403;
          }

    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          - path: /didcomm-base
            pathType: Exact
            backend:
              service:
                name: {{ include "managed-identity-wallets.fullname" . }}-acapy-base
                port:
                  number: 8000
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          - path: /didcomm-managed-wallets
            pathType: Exact
            backend:
              service:
                name: {{ include "managed-identity-wallets.fullname" . }}-acapy-mt
                port:
                  number: 8003
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "managed-identity-wallets.fullname" . }}
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.certificate.host }}
      secretName: tls-secret
{{- end}}
