{{- if not .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapy
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  acapy-endorser-admin-api-key: {{ .Values.acapy.endorser.secret.apikey | quote }}
  acapy-endorser-agent-wallet-seed: {{ .Values.acapy.endorser.secret.walletseed | quote }}
  acapy-endorser-db-account: {{ .Values.acapy.endorser.secret.dbaccount | quote }}
  acapy-endorser-db-admin: {{ .Values.acapy.endorser.secret.dbadminuser | quote }}
  acapy-endorser-db-admin-password: {{ .Values.acapy.endorser.secret.dbadminpassword | quote }}
  acapy-endorser-db-password: {{ .Values.acapy.endorser.secret.dbpassword | quote }}
  acapy-endorser-jwt-secret: {{ .Values.acapy.endorser.secret.jwtsecret | quote }}
  acapy-endorser-wallet-key: {{ .Values.acapy.endorser.secret.walletkey | quote }}
  acapy-mt-admin-api-key: {{ .Values.acapy.mt.secret.apikey | quote }}
  acapy-mt-agent-wallet-seed: {{ .Values.acapy.mt.secret.walletseed | quote }}
  acapy-mt-db-account: {{ .Values.acapy.mt.secret.dbaccount | quote }}
  acapy-mt-db-admin: {{ .Values.acapy.mt.secret.dbadminuser | quote }}
  acapy-mt-db-admin-password: {{ .Values.acapy.mt.secret.dbadminpassword | quote }}
  acapy-mt-db-password: {{ .Values.acapy.mt.secret.dbpassword | quote }}
  acapy-mt-jwt-secret: {{ .Values.acapy.mt.secret.jwtsecret | quote }}
  acapy-mt-wallet-key: {{ .Values.acapy.mt.secret.walletkey | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapypostgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.acapypostgresql.secret.password | quote }}
  postgres-password: {{ .Values.acapypostgresql.secret.postgrespassword | quote }}
  user: {{ .Values.acapypostgresql.secret.user | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.secret.password | quote }}
  postgres-password: {{ .Values.postgresql.secret.postgrespassword | quote }}
  user: {{ .Values.postgresql.secret.user | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  miw-db-jdbc-url: {{ .Values.managedIdentityWallets.secret.jdbcurl | quote }}
  miw-auth-client-id: {{ .Values.managedIdentityWallets.secret.authclientid | quote }}
  miw-auth-client-secret: {{ .Values.managedIdentityWallets.secret.authclientsecret | quote }}
  bpdm-auth-client-id: {{ .Values.managedIdentityWallets.secret.bpdmauthclientid | quote }}
  bpdm-auth-client-secret: {{ .Values.managedIdentityWallets.secret.bpdmauthclientsecret | quote }}
{{- end}}
