apiVersion: v1
kind: Service
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}
  namespace: {{ .Release.Namespace }}  
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    {{- include "managed-identity-wallets.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapy-base
spec:
  type: ClusterIP
  ports:
  - port: 8000  
  selector:
    {{- include "managed-identity-wallets.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapy-mt
spec:
  type: ClusterIP
  ports:
  - port: 8003
  selector:
    {{- include "managed-identity-wallets.selectorLabels" . | nindent 6 }}
